name: CReward
version: ${project.version}
main: cz.waterchick.creward.CReward.Main
api-version: 1.16
authors: [ Water_Chick ]
softdepend:
  - PlaceholderAPI
commands:
  creward:
    aliases:
      - cr
    description: Opens GUI menu

